# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Live from his basement, it's Sean's Content LIVE!!! Starring AlexKabanPrizon!
email: seanholmes77@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alex is a really smaht coo guhl and she likes to play board games and watch Roll Tide with me on the couch.
  Paddy is an excellent bear dog who likes to play and embark on adventures with me.
  Remi, Beetle, Motor, and Sylbio are some of the bestest most loving and entertaining cats we could ask for!
  Merry Christmas from our happy home to yours! Cheers~
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seanholmes77.com" # the base hostname & protocol for your site
twitter_username: seanholmes77
github_username:  seanholmes77

# Build settings
markdown: kramdown
